### ISSUE TITLE
interactieve buttons user

### ISSUE THREAD

**Issue by RubenErhardt** [RubenErhardt/your-tribe-profile-card#5]

**Comment by RubenErhardt** [comment]
interactieve buttons doormiddel van css en js 

```JS
 function playAudio() {
        audioElement?.play();
        if (hiddenSection) {
            hiddenSection.classList.remove('hidden');
            hiddenSection.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }

 function toggleMoreInfo() {
        if (moreInfo) {
            moreInfo.classList.toggle('hidden');
            revealButton.textContent = moreInfo.classList.contains('hidden') ? 'Click to reveal more' : 'Click to hide';
        }
    }
```
```CSS
button {
    padding: 15px 40px;
    font-size: 20px;
    border-radius: 10px;
    font-weight: bold;
    color: black;
    background: linear-gradient(135deg, #f08d03, #ee6d04);
    border: none;
    box-shadow: 0 10px 15px rgba(0, 0, 0, 0.4);
    cursor: pointer;
    transition: all 0.4s ease;
    position: relative;
}

button:hover {
    transform: scale(1.1);
}

button:active {
    transform: scale(0.95);
}`
```
